all: bignumbers.raw seven-segment-font.raw

bignumbers.raw: bignumbers.png
	convert bignumbers.png -depth 1 gray:bignumbers.raw

seven-segment-font.raw: seven-segment-font.png
	convert seven-segment-font.png -depth 1 gray:seven-segment-font.raw