all: bignumbers.raw mednumbers.raw

bignumbers.raw: bignumbers.png
	convert bignumbers.png -depth 1 gray:bignumbers.raw

mednumbers.raw: mednumbers.png
	convert mednumbers.png -depth 1 gray:mednumbers.raw

